// SPDX-FileCopyrightText: 2026 GameEngine contributors
// SPDX-License-Identifier: LicenseRef-Proprietary

#include "mirakana/audio/audio_mixer.hpp"
#include "mirakana/editor/ai_command_panel.hpp"
#include "mirakana/editor/asset_pipeline.hpp"
#include "mirakana/editor/command.hpp"
#include "mirakana/editor/content_browser.hpp"
#include "mirakana/editor/content_browser_import_panel.hpp"
#include "mirakana/editor/game_module_driver.hpp"
#include "mirakana/editor/generated_game_studio.hpp"
#include "mirakana/editor/gltf_mesh_catalog.hpp"
#include "mirakana/editor/history.hpp"
#include "mirakana/editor/input_rebinding.hpp"
#include "mirakana/editor/io.hpp"
#include "mirakana/editor/material_asset_preview_panel.hpp"
#include "mirakana/editor/material_authoring.hpp"
#include "mirakana/editor/material_graph_authoring.hpp"
#include "mirakana/editor/palette.hpp"
#include "mirakana/editor/play_in_editor.hpp"
#include "mirakana/editor/playtest_package_review.hpp"
#include "mirakana/editor/prefab_variant_authoring.hpp"
#include "mirakana/editor/profiler.hpp"
#include "mirakana/editor/project.hpp"
#include "mirakana/editor/project_wizard.hpp"
#include "mirakana/editor/render_backend.hpp"
#include "mirakana/editor/resource_panel.hpp"
#include "mirakana/editor/scene_authoring.hpp"
#include "mirakana/editor/scene_edit.hpp"
#include "mirakana/editor/shader_artifact_io.hpp"
#include "mirakana/editor/shader_compile.hpp"
#include "mirakana/editor/shader_tool_discovery.hpp"
#include "mirakana/editor/source_registry_browser.hpp"
#include "mirakana/editor/ui_model.hpp"
#include "mirakana/editor/viewport.hpp"
#include "mirakana/editor/viewport_shader_artifacts.hpp"
#include "mirakana/editor/workspace.hpp"
#include "mirakana/platform/clipboard.hpp"
#include "mirakana/platform/cursor.hpp"
#include "mirakana/platform/dynamic_library.hpp"
#include "mirakana/platform/file_dialog.hpp"
#include "mirakana/platform/file_watcher.hpp"
#include "mirakana/platform/filesystem.hpp"
#include "mirakana/platform/input.hpp"
#include "mirakana/platform/lifecycle.hpp"
#include "mirakana/platform/linux_file_watcher.hpp"
#include "mirakana/platform/macos_file_watcher.hpp"
#include "mirakana/platform/mobile.hpp"
#include "mirakana/platform/process.hpp"
#include "mirakana/platform/win32_process.hpp"
#include "mirakana/platform/window.hpp"
#include "mirakana/platform/windows_file_watcher.hpp"
#include "mirakana/renderer/rhi_viewport_surface.hpp"
#include "mirakana/runtime_host/desktop_runner.hpp"
#include "mirakana/ui/runtime_ui_production_stack.hpp"
#include "mirakana/ui/runtime_ui_workbench.hpp"
#include "mirakana/ui/ui.hpp"

int main() {
    return 0;
}
